#!/bin/bash
pin
pulp-admin rpm repo create --repo-id zoo_on_demand --relative-url zoo_on_demand --feed https://repos.fedorapeople.org/repos/pulp/pulp/fixtures/rpm-with-modules/ --download-policy on_demand
pulp-admin rpm repo sync run --repo-id zoo_on_demand
curl -L -O -k -v https://repos.fedorapeople.org/repos/pulp/pulp/fixtures/rpm-with-non-ascii/rpm-with-non-ascii-1-1.fc25.noarch.rpm
pulp-admin rpm repo uploads rpm --file rpm-with-non-ascii-1-1.fc25.noarch.rpm --repo-id zoo_on_demand
pulp-admin rpm repo publish run --repo-id zoo_on_demand
curl -L -k -v -o weird_rpm.rpm https://localhost/pulp/repos/zoo_on_demand/Packages/r/rpm-with-non-ascii-1-1.fc25.noarch.rpm
file weird_rpm.rpm
