#!/bin/bash

#https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os
#https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/optional/os/
R7_REMOTES=(\
https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os \
)

#rhel_7_x86_64_server
#rhel_7_x86_64_server_optional
R7_NAMES=(\
rhel_7_x86_64_server \
)

BASE=/home/ggainey/github/Pulp3/

for r in ${!R7_REMOTES[@]}; do
  echo ">>>>> "[${R7_REMOTES[$r]}] INTO [${R7_NAMES[$r]}];
  pulp rpm remote create --name "${R7_NAMES[$r]}" --url "${R7_REMOTES[$r]}" --policy on_demand \
      --client-cert=@${BASE}pulp_startup/CDN_cert/cdn_11012023.pem \
      --client-key=@${BASE}pulp_startup/CDN_cert/cdn_11012023.pem \
      --ca-cert=@${BASE}pulp_startup/CDN_cert/redhat-uep.pem
  pulp rpm repository create --name "${R7_NAMES[$r]}" --remote "${R7_NAMES[$r]}"
  pulp rpm repository sync --name "${R7_NAMES[$r]}"
  pulp rpm publication create --repository "${R7_NAMES[$r]}"
done
