#!/bin/bash

R7_REMOTES=(\
https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/os \
https://cdn.redhat.com/content/dist/rhel/server/7/7Server/x86_64/kickstart \
)
#R8_REMOTES=(\
#https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/os/ \
#https://cdn.redhat.com/content/dist/rhel8/8/x86_64/appstream/os/ \
#https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/kickstart/ \
#https://cdn.redhat.com/content/dist/rhel8/8/x86_64/appstream/kickstart \
#)
R8_REMOTES=(\
    https://cdn.redhat.com/content/dist/rhel8/8.0/x86_64/baseos \
    https://cdn.redhat.com/content/dist/rhel8/8.0/x86_64/baseos/kickstart \
)
R9_REMOTES=(\
    https://cdn.redhat.com/content/dist/rhel9/9/x86_64/appstream/os/ \
    https://cdn.redhat.com/content/dist/rhel9/9/x86_64/baseos/os/ \
)

R7_NAMES=(\
rhel_7_x86_64_server \
rhel_7_x86_64_server_kickstart \
)

R8_NAMES=(\
    rhel8_base \
    rhel8_base_ks \
)
#R8_NAMES=(\
#rhel_8_x86_64_baseos \
#rhel_8_x86_64_appstream \
#rhel_8_x86_64_baseos_kickstart \
#rhel_8_x86_64_appstream_kickstart \
#)

R9_NAMES=(\
    rhel_9_x86_64_appstream \
    rhel_9_x86_64_baseos \
)

R9=1
R8=
R7=

BASE=/home/ggainey/github/Pulp3/

if [ "${R9}" ]; then
    for r in ${!R9_REMOTES[@]}; do
      echo ">>>>> "[${R9_REMOTES[$r]}] INTO [${R9_NAMES[$r]}];
      pulp rpm remote create --name "${R9_NAMES[$r]}" --url "${R9_REMOTES[$r]}" --policy on_demand \
          --client-cert=@${BASE}pulp_startup/CDN_cert/19042024.pem \
          --client-key=@${BASE}pulp_startup/CDN_cert/19042024.pem \
          --ca-cert=@${BASE}pulp_startup/CDN_cert/redhat-uep.pem
      pulp rpm repository create --name "${R9_NAMES[$r]}" --remote "${R9_NAMES[$r]}" --autopublish
      pulp rpm distribution create --name "${R9_NAMES[$r]}" --repository "${R9_NAMES[$r]}" --base-path "${R9_NAMES[$r]}"
      pulp rpm repository sync --name "${R9_NAMES[$r]}"
    done
fi

if [ "${R8}" ]; then
    for r in ${!R8_REMOTES[@]}; do
      echo ">>>>> "[${R8_REMOTES[$r]}] INTO [${R8_NAMES[$r]}];
      pulp rpm remote create --name "${R8_NAMES[$r]}" --url "${R8_REMOTES[$r]}" --policy on_demand \
          --client-cert=@${BASE}pulp_startup/CDN_cert/cdn_11012023.pem \
          --client-key=@${BASE}pulp_startup/CDN_cert/cdn_11012023.pem \
          --ca-cert=@${BASE}pulp_startup/CDN_cert/redhat-uep.pem
      pulp rpm repository create --name "${R8_NAMES[$r]}" --remote "${R8_NAMES[$r]}"
      pulp -b rpm repository sync --name "${R8_NAMES[$r]}"
    done
fi

if [ "${R7}" ]; then
    for r in ${!R7_REMOTES[@]}; do
      echo ">>>>> "[${R7_REMOTES[$r]}] INTO [${R7_NAMES[$r]}];
      pulp rpm remote create --name "${R7_NAMES[$r]}" --url "${R7_REMOTES[$r]}" --policy on_demand \
          --client-cert=@${BASE}pulp_startup/CDN_cert/cdn_11012023.pem \
          --client-key=@${BASE}pulp_startup/CDN_cert/cdn_11012023.pem \
          --ca-cert=@${BASE}pulp_startup/CDN_cert/redhat-uep.pem
      pulp rpm repository create --name "${R7_NAMES[$r]}" --remote "${R7_NAMES[$r]}"
      pulp rpm repository sync --name "${R7_NAMES[$r]}"
    done
fi
