# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "fedora/28-cloud-base"

  config.vm.define "f28" do |f28|
    f28.vm.host_name = "f28.client"
    f28.vm.provider :libvirt do |domain, override|
        domain.memory = "2048"
        domain.cpu_mode = 'host-passthrough'
        domain.graphics_type = "spice"
        domain.video_type = "qxl"
    end
  end
end
