#!/bin/bash
pin
pulp-admin rpm repo create --repo-id zoo_straight --relative-url zoo_straight --feed \
   https://fixtures.pulpproject.org/rpm-with-modules/
pulp-admin rpm repo sync run --repo-id zoo_straight
curl -L -O -k -v \
  https://fixtures.pulpproject.org/rpm-with-non-ascii/rpm-with-non-ascii-1-1.fc25.noarch.rpm
pulp-admin rpm repo uploads rpm --file rpm-with-non-ascii-1-1.fc25.noarch.rpm --repo-id zoo_straight
pulp-admin rpm repo publish run --repo-id zoo_straight
curl -L -k -v -o weird_rpm.rpm \
  https://localhost/pulp/repos/zoo_straight/Packages/r/rpm-with-non-ascii-1-1.fc25.noarch.rpm
file weird_rpm.rpm
