#!/bin/bash
NAMES=( "SLE-12-SP2_x86_64-product" "SLE-12-SP2_x86_64-standard" )
URLS=( \
"https://updates.suse.com/SUSE/Backports/SLE-12-SP2_x86_64/product/" \
"https://updates.suse.com/SUSE/Backports/SLE-12-SP2_x86_64/standard/" \
)
TOKENS=( \
)

for r in ${!NAMES[@]}; do
  echo "Name ${NAMES[$r]}"
  # need to add sles_auth_token to pulp-cli soonest
  http POST :/pulp/api/v3/remotes/rpm/rpm/ \
      name="${NAMES[$r]}" \
      url="${URLS[$r]}" \
      sles_auth_token="${TOKENS[$r]}" \
      policy="on_demand"
  sleep 1
  pulp rpm repository create --name "${NAMES[$r]}" --remote "${NAMES[$r]}"
done

for r in ${!NAMES[@]}; do
  echo "Syncing ${NAMES[$r]}"
  pulp rpm repository sync --name "${NAMES[$r]}" --mirror
done
